language: r
cache: packages
latex: false
fortran: false
pandoc: false
warnings_are_errors: true

matrix:
  include:
    - r: oldrel
    - r: release
    - r: devel
      name: 'R: devel [valgrind]]'
      r_check_args: '--use-valgrind'
      env: VALGRIND_OPTS='--leak-check=full --track-origins=yes'
      addons:
        apt:
          packages:
            valgrind
    - os: osx
      name: osx-default

env:
  - _R_CHECK_TESTS_NLINES_=0
